### ISSUE TITLE
能否做成圆形的音乐频谱

### ISSUE THREAD

**Issue by judgelight** [margox/vudio.js#1]
我想在自己的博客上放一个带音乐频谱的歌单，但网上一直找不到效果比较好的。
你做的音乐频谱挺漂亮的，不过我觉得能够更上一层楼，能否试试看把它做成圆形的，
中间显示名字，和播放时间，背景可以插入图片。
类似这样的效果？
(https://www.bilibili.com/video/av20272434)

**Comment by margox** [comment]
哈哈，感谢大佬的关注，这个提议很不错，不过我现在手头的事情略多，周末我抽空看看吧

**Comment by judgelight** [comment]
谢谢你的回复，我后来用了这位大神的代码[https://github.com/Poppinrubo/HTML5VisualizationPlayer](url)
自己加了倒影，和自动隐藏播放栏，效果还算不错吧 [https://luzhihua.com/audio/](url)
感觉就差一个发光效果就可以打90分了~ 可惜不知道怎么加
不过如果能弄成像av20272434一样AE做出来的效果那是最好了！

**Comment by margox** [comment]
棒棒哒
